hash-format = "sha256"

[[files]]
file = "LICENSE"
hash = "e66c269d4819aaab34b49ef5220c4ddab6756f21bb5180761a4eb8561f2b7bbd"

[[files]]
file = "README.md"
hash = "f7afb9b04ddab56cce3e4abe2978caceca0fd72fec7670d8e4fae1c74badee67"

[[files]]
file = "config/yosbr/config/rrls.toml"
hash = "032ab7cc2c26e5973341f75e632e27abc5ff200726e32447e0438fb4cedce8d9"

[[files]]
file = "mods/animatica.pw.toml"
hash = "ccabf86379e6ad72c3eaef3abb3827eec2b9ab2b87882cc9bcd309250b99e7ca"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "48aa931775436c335b90ad23645f2a2ca7827a9cc437121e6746ae58c807ec6d"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "aa4a6773b5d34d3162955c3f4d15242a750dd797d82bcf1ae4fb2ca47d8ce64d"
metafile = true

[[files]]
file = "mods/caramelChat-mc1.21.1-fabric-1.2.1-SNAPSHOT.jar"
hash = "b81b6994fd501fe700f421007a5ac7f36d70fc7f98b696122b3d8193c861ab21"

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "463d0affc036cf47500c1740487316e0aa4a0c5210c73d27487d7db7e7d38315"
metafile = true

[[files]]
file = "mods/clean-f3.pw.toml"
hash = "8dbf5b28ec03d9aacebd933af529dbfb0d17aa25108baa474373165b2b989ebc"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "5d67c84143ca1e1598f6704f6377bd9c6b129ac95e08a7daee1a77a615286916"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "cce74bcd356f77feca560ed7ce9c6f6fe23d85f34b07bad1eb042932dceb13c8"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "e3dbc76d36c6fdca359b48d56d179da8399dc928dd1ff4d265041eae0d89c480"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "60edc5bd5c860d2f95e96b599e387437d573f43e60d5b956054ec5c1c18532e5"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "36d26044eeb09dc7a9cfc9be1970f4e2fdca97a8d9e51dc211bb026d4b63aa6a"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "bc32b74238286cacbef1b1e402b113a5e7821a69ac16c88c28640dcacc5a2123"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "f992222d98e84a44cad751f0a4f2ec024d51cf521c3270a2963427a3bf1b5fb7"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "cfb7bfb710512a5aa6ce3e687d53ef700b447f8e0c09ae3f9a9ff1f119d7ca8e"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "9827009bdb13feed1931d3034522e55c978e3e4cf1e92f971b299408a10297fb"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "817f300a2c0386539cbeea4ef97df5d09bb67fde18997af2e9be853937faa4d4"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "5fb9a78e57ab296c8077e6167f23eff43321dece11bbb53339fb3c00ce38b0d0"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "8d9f8e0b1e4bc21505b0505e6967480b411a004e95287088135fb17670b5070b"
metafile = true

[[files]]
file = "mods/forcecloseworldloadingscreen.pw.toml"
hash = "38dda442813eae135650869b3d09f709d74ec52edc381a697c967e9fc20ae514"
metafile = true

[[files]]
file = "mods/hswf3.pw.toml"
hash = "b1d7033dfe049cc4c199cbc0bdc6bbbacb4a71d02cfaa31c7a07b9064e635e12"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "ee56bda8b227275f3b1f694cf944aad87d2027943e722b8760c1273340257d33"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "c6bae0ba17af9b9ea48fb16e55b8cadc4313dfd057d0a528d1073b2367a68583"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "2143f25027945abd433dfdad9822b9e5519d6c01247027e7e5a9a0ce85902310"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "7b8c48f281b3b6e65d1ad9ee6e6ea13e83c26fa687377fa39d11eeafd45ac625"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "8e2a125b6c2ba0775718f185d43ba3ca50ffe40ea4ce0620c87aef66cf4ed425"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "34649e6c8a7512513ba8455f6f8431fcdb02145df6d0f18945b57b8e8a3588dc"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "a48bd4d3738edab1995567d18fb769f1625a8c919408aad3b81fc806688745d2"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "4fe5680c0425a6dccd57ab2eee1324b283a80a5a1a6799f348a243b7e738c63e"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "e95a1bfbde846aef49bc1dad1e7c70426329ab6754897f6d2e215f6894eb894b"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "cc247f7ec018cf1517317e83efdbbbd573071bfbbfbc0d59faf1ce0152db2326"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "1790a5bb7a0df73c0228512355163b8b89b64698c02bcdd16c73aca8cce068eb"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "d834e6b79315c53ddfa4020900fc062c27aa123a4f335a183561e43c8b674eaa"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "5856f4957a831c7c1fcef292186d3bfdbf29696bf541d2621544e3bec1265b02"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "5afc5700a4a0b88be9264fb6d900ff44bebd9708cd0014ae44605a7b4540747a"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "5c3dd96f42309ca38400222e0cdcf551e870e64c798fc357963233199ee3a11a"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "f037d66d7263d544828d9d6bccdb4a25977587ef9da06d4df5fd6f25230c487a"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "228ddcfbbd6d63fb2eed547479ba1b7416aa3fbe0fa88af77a6da606991e3d7d"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "708af6424c9eef8d86847d93d7c33dee603cfe7f43e0608d2d6655b642b770c4"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "b344aec1fe20466a08c85a112b8d38149c2ec6d4bb22dc1cca4582b387ba6026"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "42814c28bde508ad6e083582c46a817ed5b82724283af18e35ba0093dda8d323"
metafile = true

[[files]]
file = "mods/serveraddressspacefix.pw.toml"
hash = "302c628af50f63a1947ed3739ce3148f14aff358f74aa094b187ee19d40012b9"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "683890ca7fc8ad0e58675b99c88d3fc43e160d52863447d32d5f810bcaaaea05"
metafile = true

[[files]]
file = "mods/serverpingerfixer.pw.toml"
hash = "79788a85c3b4f8123c79f1f646679c3670d145776f3c67f2de3a4e703c138666"
metafile = true

[[files]]
file = "mods/smooth-scrolling-refurbished.pw.toml"
hash = "8a9daf485b1289202a8e840f66d70a0eb8a06c2079fd812264ad80f146583978"
metafile = true

[[files]]
file = "mods/sodium-core-shader-support.pw.toml"
hash = "b9413cc995c0987287c9725b150a32ad96706c11f887f15940c669045ae3575c"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "fae1accc78ee1efb658b436ab760a616fa83f4f2832b09d215cbdd7f5c914557"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "56a256605d83894948298a83e0c81e5b71b000f9b0ee123174f7556adf722950"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "07efbee613980cae029622c1bbdc8d89523c26e932c32e3fe4359e3a4d0e0622"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "125171299b2cd518eb3a27bb421ff39e5580b1eac900c9498df1d1a3cdb7a865"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "ece4e12edcfea92d4eea53843c17641d1529dc15a138bd8a1f24fa4cc481adf9"
metafile = true

[[files]]
file = "mods/xanders-sodium-options.pw.toml"
hash = "b264bbc58381f162f9737b83a8bee7b246e72fd946f0ca1b4e9917d55030a3ce"
metafile = true

[[files]]
file = "mods/xplus-contingameime.pw.toml"
hash = "9a616241cd22b6dd7322f09f430a63c0f66398f5335cc7a28204cbec11d7dded"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "23ef9d9c164ebe23ad26ff89669b1d13d7ec33ce0bab05d4f509a3647fe086cc"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "3bf16ef57d8e5a916e8971ab9cc7cd90644d82932233b7e1e2293d95680fac4b"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "1f5a66967f2e47062a4dafef38f467dc47ac51f3c645a6fb979b21dd0adf64c4"
metafile = true

[[files]]
file = "resourcepacks/-translatenotenoughanimations.pw.toml"
hash = "1b6a4e6ff38849733bbc288bd0004e3624ffb254e32d1ef4fe35dd5eed62991b"
metafile = true

[[files]]
file = "resourcepacks/advancementinforeloaded汉化.zip"
hash = "6482769caacfe7f58354750928fe1304245f22a3a6954a2ed7479118db74911e"

[[files]]
file = "resourcepacks/chat-reporting-helper.pw.toml"
hash = "66cad8ebb10f5cc80b7d57c97c87439783b55f9da4485b08221ed99c37d6c81b"
metafile = true

[[files]]
file = "resourcepacks/chinese-end-poem.pw.toml"
hash = "d3bccf8ea2002ce601e17e000dd7a3b3b882dbc285eedb6d8ed9e0ea2378b9da"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode.pw.toml"
hash = "cd2e459b51947aedd689cd7c3f6219b02a23268b44b8cb00fda3b4c2b7163a37"
metafile = true

[[files]]
file = "resourcepacks/even-better-enchants.pw.toml"
hash = "22414b0366702590284be457e3541e08486c684b76bdf538c2d0f42fdaae90e0"
metafile = true

[[files]]
file = "resourcepacks/fast-better-grass.pw.toml"
hash = "42ca3f662c4f8072f3896814fcdcf5971e8b1b8c429f6a08444e7a86087e10ec"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "8d4ef54b5da8007d17fea93efb1584d3d41b05e1b6953eeb7dc39210eb9b0255"
metafile = true

[[files]]
file = "resourcepacks/masa-mod-translationpack.pw.toml"
hash = "08e1387d59dcd1fc090ce0f5e2f6337c83a5759aa9c97968f609aba5efc20886"
metafile = true

[[files]]
file = "resourcepacks/poeme-de-l-end.pw.toml"
hash = "1432fc9395eedfde33c5bb0433c24225c2f8fdcff920bfbdc0ef01af94d15f7e"
metafile = true

[[files]]
file = "resourcepacks/programmer-art-fix.pw.toml"
hash = "d5e3e235001076c36124d864d56d2aaa77188ffeced1b717dbf56badf711bb66"
metafile = true

[[files]]
file = "resourcepacks/son-siir-turkce-ceviri.pw.toml"
hash = "60c987f7404660c00e7e4d189e714fa7574e8da4b6aff8d8c20528f3d406bef9"
metafile = true

[[files]]
file = "resourcepacks/translate-mods.pw.toml"
hash = "156b3ce4e961a5cc61eb8e1e33b0adc9f63bfe2b42bd36a80695ef4422b5318c"
metafile = true

[[files]]
file = "resourcepacks/translations-for-sodium.pw.toml"
hash = "3f73423da0e8536ba87c88fcbc049f69b4952fd5343226593d4165cf8a8201ca"
metafile = true

[[files]]
file = "resourcepacks/xk-redstone-display.pw.toml"
hash = "a80ae6abafd302a5de7c47ae3b0f6712698fdacf4366c49c7f6363fafc19b50a"
metafile = true

[[files]]
file = "resourcepacks/ziyun-redstone-cover.pw.toml"
hash = "64bd11dfecff4b8879df29ac8694b78990caf1fc5f0206c703433441abfad38e"
metafile = true

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
hash = "7d24847b21badd61c256acb19ea4a3b7e1e65c910f4b3647fdcdbbf5df826691"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "2fef9da2480d761a89972b2b82f3154d357b97d547284bd84162f6cc4fbb759c"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "96657ed5f8448d1c6e216425e5d7d16003c80ac390803767473748dcb6e581c2"
metafile = true
